### ISSUE TITLE
Create an ent schema with invalid `creator` data type

### ISSUE THREAD

**Issue by ahmedxfn** [Yiling-J/carrier#2]
When creating carrier with `ent` schema, it generates factories with invalid data type since the data type is hardcoded in the template here https://github.com/Yiling-J/carrier/blob/master/template/carrier.tmpl#L32,
```
{{$DynamicParams = $RawSchemaName | printf "creator *ent.%sCreate"}}
```

which generates
```
func(ctx context.Context, i *EntUserMutator, c int, creator *ent.UserCreate)
```

and in my case it should be like this
```
func(ctx context.Context, i *EntUserMutator, c int, creator *model.UserCreate)
```

The generation should be generic to whatever the ent directory the user has, in my case I call it `model` not `ent`
```
├── db/
│   ├── model/     # ent generated files
│   │    └── user/
│   │        └── user.go
│   └── carrier/
│           └── schema.go
```

**Comment by Yiling-J** [comment]
@r4ndomx Thanks for reporting this issue. This is definitely a bug and I will fix soon and let you know🙏

**Comment by Yiling-J** [comment]
@r4ndomx Can you switch to master branch and try?
